spring:
  application:
    name: auth-service
  config:
    import: "classpath:/common-application.yml"
  datasource:
    url: jdbc:postgresql://${apiforge.datasource.host}/${apiforge.datasource.db-name}?${apiforge.datasource.params}
    username: ${apiforge.datasource.username}
    password: ${apiforge.datasource.password}
    driver-class-name: ${apiforge.datasource.driver-class-name}
  jpa:
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com
server:
  port: 7081
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET:apiforge-headless-cms-secret-key-minimum-256-bits-required-for-hs256}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-secret: ${JWT_REFRESH_SECRET:apiforge-headless-cms-refresh-secret-key-minimum-256-bits-required}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
