spring:
  application:
    name: content-type-service
  datasource:
    url: jdbc:postgresql://ep-lingering-rain-ahbp23u9-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
server:
  port: 8082
