spring:
  application:
    name: content-type-service
  config:
    import: "classpath:/common-application.yml"
  datasource:
    url: jdbc:postgresql://${apiforge.datasource.host}/${apiforge.datasource.db-name}?${apiforge.datasource.params}
    username: ${apiforge.datasource.username}
    password: ${apiforge.datasource.password}
    driver-class-name: ${apiforge.datasource.driver-class-name}
  jpa:
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: dev
server:
  port: 7082
